name = "quilt-anatoly"
author = "krashd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bfb52b1b30d5368613ffbb15053ed4022d3b97614a524c06484e3469886015c"

[versions]
minecraft = "1.20"
quilt = "0.19.0-beta.18"
